// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"pastureen/librarian/ent/dblink"
	"pastureen/librarian/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DbLinkDelete is the builder for deleting a DbLink entity.
type DbLinkDelete struct {
	config
	hooks    []Hook
	mutation *DbLinkMutation
}

// Where appends a list predicates to the DbLinkDelete builder.
func (dld *DbLinkDelete) Where(ps ...predicate.DbLink) *DbLinkDelete {
	dld.mutation.Where(ps...)
	return dld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dld *DbLinkDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, dld.sqlExec, dld.mutation, dld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (dld *DbLinkDelete) ExecX(ctx context.Context) int {
	n, err := dld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dld *DbLinkDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(dblink.Table, sqlgraph.NewFieldSpec(dblink.FieldID, field.TypeUUID))
	if ps := dld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	dld.mutation.done = true
	return affected, err
}

// DbLinkDeleteOne is the builder for deleting a single DbLink entity.
type DbLinkDeleteOne struct {
	dld *DbLinkDelete
}

// Where appends a list predicates to the DbLinkDelete builder.
func (dldo *DbLinkDeleteOne) Where(ps ...predicate.DbLink) *DbLinkDeleteOne {
	dldo.dld.mutation.Where(ps...)
	return dldo
}

// Exec executes the deletion query.
func (dldo *DbLinkDeleteOne) Exec(ctx context.Context) error {
	n, err := dldo.dld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{dblink.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dldo *DbLinkDeleteOne) ExecX(ctx context.Context) {
	if err := dldo.Exec(ctx); err != nil {
		panic(err)
	}
}
