// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"pastureen/librarian/ent/dbtag"
	"pastureen/librarian/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DbTagDelete is the builder for deleting a DbTag entity.
type DbTagDelete struct {
	config
	hooks    []Hook
	mutation *DbTagMutation
}

// Where appends a list predicates to the DbTagDelete builder.
func (dtd *DbTagDelete) Where(ps ...predicate.DbTag) *DbTagDelete {
	dtd.mutation.Where(ps...)
	return dtd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dtd *DbTagDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, dtd.sqlExec, dtd.mutation, dtd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (dtd *DbTagDelete) ExecX(ctx context.Context) int {
	n, err := dtd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dtd *DbTagDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(dbtag.Table, sqlgraph.NewFieldSpec(dbtag.FieldID, field.TypeString))
	if ps := dtd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dtd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	dtd.mutation.done = true
	return affected, err
}

// DbTagDeleteOne is the builder for deleting a single DbTag entity.
type DbTagDeleteOne struct {
	dtd *DbTagDelete
}

// Where appends a list predicates to the DbTagDelete builder.
func (dtdo *DbTagDeleteOne) Where(ps ...predicate.DbTag) *DbTagDeleteOne {
	dtdo.dtd.mutation.Where(ps...)
	return dtdo
}

// Exec executes the deletion query.
func (dtdo *DbTagDeleteOne) Exec(ctx context.Context) error {
	n, err := dtdo.dtd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{dbtag.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dtdo *DbTagDeleteOne) ExecX(ctx context.Context) {
	if err := dtdo.Exec(ctx); err != nil {
		panic(err)
	}
}
