// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"pastureen/librarian/ent/dblink"
	"pastureen/librarian/ent/dbtag"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DbTagCreate is the builder for creating a DbTag entity.
type DbTagCreate struct {
	config
	mutation *DbTagMutation
	hooks    []Hook
}

// SetID sets the "id" field.
func (dtc *DbTagCreate) SetID(s string) *DbTagCreate {
	dtc.mutation.SetID(s)
	return dtc
}

// AddLinkIDs adds the "links" edge to the DbLink entity by IDs.
func (dtc *DbTagCreate) AddLinkIDs(ids ...string) *DbTagCreate {
	dtc.mutation.AddLinkIDs(ids...)
	return dtc
}

// AddLinks adds the "links" edges to the DbLink entity.
func (dtc *DbTagCreate) AddLinks(d ...*DbLink) *DbTagCreate {
	ids := make([]string, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dtc.AddLinkIDs(ids...)
}

// Mutation returns the DbTagMutation object of the builder.
func (dtc *DbTagCreate) Mutation() *DbTagMutation {
	return dtc.mutation
}

// Save creates the DbTag in the database.
func (dtc *DbTagCreate) Save(ctx context.Context) (*DbTag, error) {
	return withHooks(ctx, dtc.sqlSave, dtc.mutation, dtc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dtc *DbTagCreate) SaveX(ctx context.Context) *DbTag {
	v, err := dtc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dtc *DbTagCreate) Exec(ctx context.Context) error {
	_, err := dtc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dtc *DbTagCreate) ExecX(ctx context.Context) {
	if err := dtc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dtc *DbTagCreate) check() error {
	return nil
}

func (dtc *DbTagCreate) sqlSave(ctx context.Context) (*DbTag, error) {
	if err := dtc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dtc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dtc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected DbTag.ID type: %T", _spec.ID.Value)
		}
	}
	dtc.mutation.id = &_node.ID
	dtc.mutation.done = true
	return _node, nil
}

func (dtc *DbTagCreate) createSpec() (*DbTag, *sqlgraph.CreateSpec) {
	var (
		_node = &DbTag{config: dtc.config}
		_spec = sqlgraph.NewCreateSpec(dbtag.Table, sqlgraph.NewFieldSpec(dbtag.FieldID, field.TypeString))
	)
	if id, ok := dtc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if nodes := dtc.mutation.LinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   dbtag.LinksTable,
			Columns: dbtag.LinksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dblink.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DbTagCreateBulk is the builder for creating many DbTag entities in bulk.
type DbTagCreateBulk struct {
	config
	err      error
	builders []*DbTagCreate
}

// Save creates the DbTag entities in the database.
func (dtcb *DbTagCreateBulk) Save(ctx context.Context) ([]*DbTag, error) {
	if dtcb.err != nil {
		return nil, dtcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(dtcb.builders))
	nodes := make([]*DbTag, len(dtcb.builders))
	mutators := make([]Mutator, len(dtcb.builders))
	for i := range dtcb.builders {
		func(i int, root context.Context) {
			builder := dtcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DbTagMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dtcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dtcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dtcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dtcb *DbTagCreateBulk) SaveX(ctx context.Context) []*DbTag {
	v, err := dtcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dtcb *DbTagCreateBulk) Exec(ctx context.Context) error {
	_, err := dtcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dtcb *DbTagCreateBulk) ExecX(ctx context.Context) {
	if err := dtcb.Exec(ctx); err != nil {
		panic(err)
	}
}
