// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DbLink is the predicate function for dblink builders.
type DbLink func(*sql.Selector)

// DbTag is the predicate function for dbtag builders.
type DbTag func(*sql.Selector)
