[workspace]
members = [
  "print_table",
  "csv_iterator",
  "cli",
  "actix_poc",
  "auth_contracts",
  "auth_api",
  "auth_service",
  "reverse_proxy",
  "components",
  "blog_site",
  "post_generator"
]
