// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DbLinksColumns holds the columns for the "db_links" table.
	DbLinksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "title", Type: field.TypeString},
		{Name: "date", Type: field.TypeTime},
		{Name: "url", Type: field.TypeString},
		{Name: "subtitle", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "image_url", Type: field.TypeString, Nullable: true},
		{Name: "image_alt", Type: field.TypeString, Nullable: true},
	}
	// DbLinksTable holds the schema information for the "db_links" table.
	DbLinksTable = &schema.Table{
		Name:       "db_links",
		Columns:    DbLinksColumns,
		PrimaryKey: []*schema.Column{DbLinksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "dblink_date",
				Unique:  false,
				Columns: []*schema.Column{DbLinksColumns[2]},
			},
		},
	}
	// DbTagsColumns holds the columns for the "db_tags" table.
	DbTagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString},
	}
	// DbTagsTable holds the schema information for the "db_tags" table.
	DbTagsTable = &schema.Table{
		Name:       "db_tags",
		Columns:    DbTagsColumns,
		PrimaryKey: []*schema.Column{DbTagsColumns[0]},
	}
	// DbLinkTagsColumns holds the columns for the "db_link_tags" table.
	DbLinkTagsColumns = []*schema.Column{
		{Name: "db_link_id", Type: field.TypeUUID},
		{Name: "db_tag_id", Type: field.TypeUUID},
	}
	// DbLinkTagsTable holds the schema information for the "db_link_tags" table.
	DbLinkTagsTable = &schema.Table{
		Name:       "db_link_tags",
		Columns:    DbLinkTagsColumns,
		PrimaryKey: []*schema.Column{DbLinkTagsColumns[0], DbLinkTagsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "db_link_tags_db_link_id",
				Columns:    []*schema.Column{DbLinkTagsColumns[0]},
				RefColumns: []*schema.Column{DbLinksColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "db_link_tags_db_tag_id",
				Columns:    []*schema.Column{DbLinkTagsColumns[1]},
				RefColumns: []*schema.Column{DbTagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DbLinksTable,
		DbTagsTable,
		DbLinkTagsTable,
	}
)

func init() {
	DbLinkTagsTable.ForeignKeys[0].RefTable = DbLinksTable
	DbLinkTagsTable.ForeignKeys[1].RefTable = DbTagsTable
}
