[package]
name = "prpc_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prpc_core = { path = "../prpc_core" }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
