name: Deploy design system (dev)

on:
  workflow_dispatch:

jobs:
  deploy_design_system:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Deploy design system
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DESIGN_SYSTEM_BASE_URL: ${{ vars.DESIGN_SYSTEM_URL }}
        run: cd golang/design && ./deploy.sh dev

