name: Deploy auth service (dev)

on:
  workflow_dispatch:

jobs:
  deploy_auth_service:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Deploy auth service
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AUTH_SERVICE_SECRET: ${{ secrets.AUTH_SERVICE_SECRET }}
          AUTH_SERVICE_DB_CONN_STR: ${{ secrets.AUTH_SERVICE_DB_CONN_STR }}
          AUTH_WEB_SERVICE_LISTEN_ADDR: ${{ secrets.AUTH_WEB_SERVICE_LISTEN_ADDR }}
        run: cd rust/auth_web_service && ./deploy.sh

