name: Deploy reverse proxy (dev)

on:
  workflow_dispatch:

jobs:
  deploy_reverse_proxy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Deploy reverse proxy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          REVERSE_PROXY_LISTEN_ADDR: ${{ vars.LAMBDA_LISTEN_ADDR }}
          REVERSE_PROXY_DESIGN_SYSTEM_URL: ${{ vars.DESIGN_SYSTEM_URL }}
          REVERSE_PROXY_STATIC_ASSETS_URL: ${{ vars.STATIC_ASSETS_URL }}
          REVERSE_PROXY_BLOG_URL: ${{ vars.BLOG_URL }}
          REVERSE_PROXY_BASE_URL: ${{ vars.REVERSE_PROXY_URL }}
        run: cd rust/reverse_proxy && ./deploy.sh dev

